apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-echo
  template:
    metadata:
      labels:
        app: busybox-echo
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["/bin/sh", "-c"]
        args: ["echo Hello2 && sleep 600"]