---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: echo-appset-duplicated
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/GonzaV/argocd-applications.git
      revision: HEAD
      directories:
      - path: manifests/busybox-duplicated
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/GonzaV/argocd-applications.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
        syncOptions:
        - ApplyOutOfSyncOnly=true
        - Validate=true
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - ServerSideApply=true
        - FailOnSharedResource=true
        retry:
          limit: 1
          backoff:
            duration: 2m
            factor: 2
            maxDuration: 3m
